Repository gazebosim/gz-plugin, pull requests merged in 2021-03, with the labels that each got.

#45 Master branch updates
  .github/workflows/ci.yml
  tutorials/02_installation.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#46 🎈 1.2.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#47 Update README.md
  README.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#48 Include windows instructions in examples README.md and fix examples to compile them on Windows
  examples/CMakeLists.txt
  examples/README.md
  examples/plugins/CrashBot.cc
  examples/robot.cc
Labels: Windows, documentation, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#49 🎈 1.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
