Repository gazebosim/gz-plugin, pull requests merged in 2022-08, with the labels that each got.

#98 Merge ign-plugin1 ➡️ main
  CMakeLists.txt
  README.md
  loader/CMakeLists.txt
  loader/conf/CMakeLists.txt
  loader/conf/plugin.bash_completion.sh
  loader/src/gz_TEST.cc
Labels: 🌱 garden

#99 ⬆️ Bump main to 3.0.0~pre1
  CMakeLists.txt
  Changelog.md
  examples/CMakeLists.txt
Labels: 🌱 garden

#100 ign -> gz : Remove redundant namespace references
  loader/src/ign.cc
Labels: 🏰 citadel, 🏯 fortress, ign to gz

#103 🎈 1.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress

#104 Hotfix plugin header installation directory
  core/CMakeLists.txt
Labels: bug, ign to gz, Breaking change

#102 Add option to use RTLD_NODELETE when loading a library
  loader/include/gz/plugin/Loader.hh
  loader/src/Loader.cc
  test/integration/CMakeLists.txt
  test/integration/plugin_unload.hh
  test/integration/plugin_unload_with_nodelete.cc
  test/integration/plugin_unload_without_nodelete.cc
  test/plugins/CMakeLists.txt
  test/plugins/InstanceCounter.cc
  test/plugins/InstanceCounter.hh
Labels: bug, 🌱 garden
