Repository gazebosim/gz-plugin, pull requests merged in 2022-06, with the labels that each got.

#89 [ign -> gz] CMake functions
  CMakeLists.txt
  core/CMakeLists.txt
  core/include/gz/plugin/CMakeLists.txt
  loader/CMakeLists.txt
  loader/conf/CMakeLists.txt
  loader/conf/plugin.yaml.in
  register/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#87 ign -> gz Macro Migration : gz-plugin
  Migration.md
  MigrationFromCommon.md
  core/include/gz/plugin/EnablePluginFromThis.hh
  core/include/gz/plugin/Factory.hh
  core/include/gz/plugin/Info.hh
  core/include/gz/plugin/Plugin.hh
  core/include/gz/plugin/WeakPluginPtr.hh
  core/include/gz/plugin/detail/Factory.hh
  examples/plugins/BoxEnvironment.cc
  examples/plugins/CautiousBot.cc
  examples/plugins/CrashBot.cc
  examples/plugins/ExponentialODE.cc
  examples/plugins/ForwardEuler.cc
  examples/plugins/PolynomialODE.cc
  examples/plugins/RungeKutta4.cc
  examples/robot.cc
  loader/include/gz/plugin/Loader.hh
  loader/src/Loader.cc
  loader/src/cmd/ign.cc
  loader/src/cmd/ign.hh
  loader/src/cmd/plugin_main.cc
  loader/src/ign_TEST.cc
  register/include/gz/plugin/Register.hh
  register/include/gz/plugin/RegisterMore.hh
  register/include/gz/plugin/detail/Register.hh
  register/include/ignition/plugin/Register.hh
  register/include/ignition/plugin/RegisterMore.hh
  test/integration/CMakeLists.txt
  test/integration/factory.cc
  test/integration/plugin.cc
  test/integration/templated_plugins.cc
  test/performance/plugin_specialization.cc
  test/plugins/BadPluginAPIVersionNew.cc
  test/plugins/BadPluginAPIVersionOld.cc
  test/plugins/BadPluginAlign.cc
  test/plugins/BadPluginNoInfo.cc
  test/plugins/BadPluginSize.cc
  test/plugins/CMakeLists.txt
  test/plugins/DummyPlugins.cc
  test/plugins/DummyPluginsOtherTranslationUnit.cc
  test/plugins/FactoryPlugins.cc
  test/plugins/TemplatedPlugins.cc
  test/static_assertions/plugin_no_base_class.cc
  test/static_assertions/plugin_wrong_base_class.cc
Labels: 🌱 garden, needs upstream release, ign to gz

#88 ign -> gz CLI Migration : gz-plugin
  CMakeLists.txt
  Changelog.md
  README.md
  loader/CMakeLists.txt
  loader/conf/CMakeLists.txt
  loader/src/cmd/CMakeLists.txt
  loader/src/cmd/gz.cc
  loader/src/cmd/gz.hh
  loader/src/cmd/plugin_main.cc
  loader/src/gz_TEST.cc
  tutorials/02_installation.md
Labels: 🌱 garden, ign to gz

#82 Rename CMake project to gz
  CMakeLists.txt
  core/CMakeLists.txt
  examples/CMakeLists.txt
  examples/plugins/CMakeLists.txt
  loader/src/cmd/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#90 ign -> gz Partial Docs Migration and Project Name Followups : gz-plugin
  CMakeLists.txt
  Changelog.md
  Migration.md
  MigrationFromCommon.md
  api.md.in
  appveyor.yml
  examples/README.md
  examples/integrators.cc
  loader/CMakeLists.txt
  loader/conf/plugin.yaml.in
  loader/src/cmd/CMakeLists.txt
  tutorials.md.in
  tutorials/01_intro.md
  tutorials/02_installation.md
Labels: 🌱 garden
