Repository gazebosim/gz-plugin, pull requests merged in 2022-07, with the labels that each got.

#92 Install yaml tools file to gz
  CMakeLists.txt
  loader/conf/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#94 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, 🏯 fortress, QA

#95 Clean unused lambda capture warning
  loader/src/cmd/plugin_main.cc
Labels: 🌱 garden

#93 ign -> gz Provisional Finale: Source Migration : gz-plugin
  .github/ci/packages.apt
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  MigrationFromCommon.md
  README.md
  api.md.in
  appveyor.yml
  core/CMakeLists.txt
  core/include/gz/plugin/detail/SpecializedPlugin.hh
  examples/CMakeLists.txt
  examples/integrators.cc
  examples/plugins/RungeKutta4.cc
  examples/robot.cc
  loader/CMakeLists.txt
  loader/conf/CMakeLists.txt
  loader/src/cmd/CMakeLists.txt
  loader/src/cmd/cmdplugin.rb.in
  loader/src/cmd/gz.hh
  loader/src/cmd/plugin_main.cc
  register/CMakeLists.txt
  register/include/gz/plugin/detail/Register.hh
  test/integration/plugin.cc
  test/integration/templated_plugins.cc
  test/performance/CMakeLists.txt
  tutorials.md.in
  tutorials/02_installation.md
Labels: 🌱 garden, ign to gz

#96 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  loader/conf/CMakeLists.txt
  loader/src/cmd/CMakeLists.txt
  tutorials.md.in
Labels: 🏰 citadel, 🏯 fortress, needs upstream release, ign to gz

#97 Static plugins
  core/include/gz/plugin/Plugin.hh
  core/include/gz/plugin/PluginPtr.hh
  core/include/gz/plugin/detail/PluginPtr.hh
  core/src/Plugin.cc
  loader/CMakeLists.txt
  loader/include/gz/plugin/Loader.hh
  loader/include/gz/plugin/detail/Loader.hh
  loader/include/gz/plugin/detail/Registry.hh
  loader/include/gz/plugin/detail/StaticRegistry.hh
  loader/src/Loader.cc
  loader/src/detail/Registry.cc
  loader/src/detail/StaticRegistry.cc
  register/include/gz/plugin/RegisterStatic.hh
  register/include/gz/plugin/detail/Common.hh
  register/include/gz/plugin/detail/Register.hh
  register/include/gz/plugin/detail/RegisterStatic.hh
  register/include/ignition/plugin/RegisterStatic.hh
  register/include/ignition/plugin/detail/RegisterStatic.hh
  test/integration/CMakeLists.txt
  test/integration/static_plugins.cc
  test/plugins/CMakeLists.txt
  test/plugins/DummyStaticPlugin.cc
Labels: enhancement, 🌱 garden
