Repository gazebosim/gz-plugin, pull requests merged in 2023-03, with the labels that each got.

#113 Bazel build rules for garden
  BUILD.bazel
  loader/src/Loader.cc
  loader/src/Loader_TEST.cc
  test/BUILD.bazel
Labels: 🌱 garden

#114 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel, 🏯 fortress

#115 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel, 🏯 fortress

#116 Merge ign-plugin1 ➡️ gz-plugin2
  .github/workflows/ci.yml
  COPYING
  LICENSE
Labels: 🌱 garden, 🎵 harmonic
